### PR TITLE
Adding consistency while changing scenes.

### PR DESCRIPTION
**Pull request by MaverickEngan**
The player will now stay in the location where he encountered the enemy and the enemy will be removed from the map after encountering the player after the combat screen. I have also moved the methods that I had in place for combat in the player class to the autoloaded globalplayer allowing for changes in health and stats to be permanent. As shown with a small example when in the demo combat screen using the take damage button it will save the damage when returning to the map.

### CODE REVIEW

**Comment by MaverickEngan** [comment]
Fixed issues that were caused while merging other branches seems to be working now (if someone else could also take a look at it that would be great), however there is a slight issue with the camera not showing the health counter that I had made when the page was static and the buttons in the temporary combat screen are also off screen. If this is an easy fix that someone is aware of I would appreciate it if not I will tweak things tomorrow.

**Comment by Luke-Ed** [comment]
Brendan modified the camera settings which is why your health bar is off screen, and the fight scene is hard to use. I'll take a look at changing it with the scene change, and then it should be good to merge.

**Comment by MaverickEngan** [comment]
Whenever I tried to solve the merging conflicts from when Elijah merged his branch, I thought I did it in a way that wouldn't mess anything up but now it won't even open the project due to something about the game version never being chosen so looking through what I had to change and don't see the problem yet. Still looking through it if someone could also give it a look over and try to find the issue that would be helpful.

**Comment by MaverickEngan** [comment]
Okay so turns out it isn't a problem with my code being pushed (I did however revert the "fixes" from earlier in order to get it back to a stable position. But I can't even run the main branch on my machine due to messed up dependencies. This merge should be ready to go unsure if you guys want to go ahead and merge this then fix the dependencies or fix the dependencies issues in main first then send this in. Either way I am keeping a safe file of the current project (minus Elijah's changes).

**Pull request merged**
